<option value="">Select Committee</option>
<option <?php echo $general ?> value="General IEEE">General IEEE</option>
<option <?php echo $aerial ?> value="Aerial Robotics">Aerial Robotics</option>
<option <?php echo $computer ?> value="Computer Society">Computer Society</option>
<option <?php echo $embs ?> value="EMBS">EMBS</option>
<option <?php echo $mtts ?> value="MTT-S">MTT-S</option>
<option <?php echo $professional ?> value="Professional">Professional</option>
<option <?php echo $learning ?> value="Learning">Learning</option>
<option <?php echo $racing ?> value="Racing">Racing</option>
<option <?php echo $rov ?> value="ROV">ROV</option>
<option <?php echo $social ?> value="Social">Social</option>
<option <?php echo $social ?> value="SOGA">SOGA</option>